/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/_authenticated/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/_authenticated/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/grades': typeof AuthenticatedGradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/grades': typeof AuthenticatedGradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/grades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/grades'
  id: '__root__' | '/' | '/_authenticated/calendar' | '/_authenticated/grades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
